### ISSUE TITLE
Cannot make Invana works

### ISSUE THREAD

**Issue by IvanGDR** [invanalabs/invana-engine#4]
Hi,

I am using a Janusgraph Cluster with cassandra CQL and Solr. Using as access point ConfiguredGraphManagement.

I am trying to use Invana Studio/Engine but I cannot make it works, after submitting from the studio "http://192.168.0.9:8200/graphql" the studio becomes blank and stuck there, there is not any message received from the studio at all.
--------------------------------------------
ivang@dell15-3552:/opt$ invana/invana-studio
IsDev false
startURL file:///opt/invana/resources/app.asar/build/index.html#/add
--------------------------------------------

On the other hand, the invana engine is being executed from an anaconda/python environment as follows:
----------------------------------------------
(invana) ivang@dell15-3552:~$ export GREMLIN_SERVER_URL="ws://192.168.0.9:8182/gremlin"
(invana) ivang@dell15-3552:~$ invana-engine-start
Starting Invana Engine server
Using GREMLIN_SERVER_URL ws://192.168.0.9:8182/gremlin
INFO:     Started server process [11381]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8200 (Press CTRL+C to quit)
-----------------------------------------------

This is a log returned from the engine after playing around when opening on a the browser the address http://192.168.0.9:8200/graphql

ERROR:graphql.execution.executor:An error occurred while resolving field GremlinQuery.filterVertex
Traceback (most recent call last):
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/invana_engine/server/schemas/query.py", line 119, in resolve_filter_vertex
    label=label, namespace=namespace, query=query, limit=limit, skip=skip
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/invana_engine/gremlin/base.py", line 91, in read_many
    return self._read_many(label=label, namespace=namespace, query=query, limit=limit, skip=skip)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/invana_engine/gremlin/vertex.py", line 88, in _read_many
    for _ in filtered_data.elementMap().toList():
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/process/traversal.py", line 58, in toList
    return list(iter(self))
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/process/traversal.py", line 48, in __next__
    self.traversal_strategies.apply_strategies(self)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/process/traversal.py", line 573, in apply_strategies
    traversal_strategy.apply(traversal)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/remote_connection.py", line 149, in apply
    remote_traversal = self.remote_connection.submit(traversal.bytecode)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/driver_remote_connection.py", line 56, in submit
    results = result_set.all().result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/resultset.py", line 90, in cb
    f.result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/connection.py", line 83, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/protocol.py", line 112, in data_received
    raise GremlinServerError(message["status"])
gremlin_python.driver.protocol.GremlinServerError: 499: The traversal source [g] for alias [g] is not configured on the server.
ERROR:graphql.execution.utils:Traceback (most recent call last):
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/invana_engine/server/schemas/query.py", line 119, in resolve_filter_vertex
    label=label, namespace=namespace, query=query, limit=limit, skip=skip
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/invana_engine/gremlin/base.py", line 91, in read_many
    return self._read_many(label=label, namespace=namespace, query=query, limit=limit, skip=skip)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/invana_engine/gremlin/vertex.py", line 88, in _read_many
    for _ in filtered_data.elementMap().toList():
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/process/traversal.py", line 58, in toList
    return list(iter(self))
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/process/traversal.py", line 48, in __next__
    self.traversal_strategies.apply_strategies(self)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/process/traversal.py", line 573, in apply_strategies
    traversal_strategy.apply(traversal)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/remote_connection.py", line 149, in apply
    remote_traversal = self.remote_connection.submit(traversal.bytecode)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/driver_remote_connection.py", line 56, in submit
    results = result_set.all().result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/resultset.py", line 90, in cb
    f.result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/connection.py", line 83, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/home/ivang/anaconda3/envs/invana/lib/python3.7/site-packages/gremlin_python/driver/protocol.py", line 112, in data_received
    raise GremlinServerError(message["status"])
graphql.error.located_error.GraphQLLocatedError: 499: The traversal source [g] for alias [g] is not configured on the server.

INFO:     192.168.0.9:43912 - "POST /graphql HTTP/1.1" 400 Bad Request

NOTE:
when I return to the studio after killing it, this message appears:
No match found for /opt/invana/resources/app.asar/build/index.html 
<--- go to home

Any help will be appreciated.

Thanks

**Comment by rrmerugu** [comment]
similar to #2
